version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    # environment:
    #   - MYSQL_DATABASE=devdb
    #   - MYSQL_ROOT_PASSWORD=devpassword
    env_file:
      - ../.env
    ports:
      - '3306:3306'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  frontend:
    image: sheffessions_fe 
    build:
      context: ../frontend/sheffessions
    ports:
      - '3000:3000'
    env_file:
      - ../.env

  backend:
    image: sheffessions_api
    build:
      context: ../backend/sheffessions_api  # path to where the Dockerfile for backend is
      dockerfile:  Dockerfile.dev
    ports:
      - '8080:8080'  # assuming your backend runs on port 8080
    volumes:
      - ../backend/sheffessions_api:/app
    env_file:
      - ../.env

volumes:
  db:
    driver: local
