# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
name: Go

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache-dependency-path: subdir/go.sum

    - name: Fetch dependencies
      working-directory: ./backend/sheffessions_api
      run: go get -v ./...

    - name: Build for AWS Lambda
      working-directory: ./backend/sheffessions_api
      run: |
        GOOS=linux GOARCH=amd64 go build -o main .
        zip deployment.zip main

    - name: Test
      working-directory: ./backend/sheffessions_api
      run: go test -v .

    # - name: Configure AWS credentials
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: us-west-2  # Change this to your AWS region
    #
    # - name: Deploy to AWS Lambda
    #   run: |
    #     aws lambda update-function-code --function-name YOUR_LAMBDA_FUNCTION_NAME --zip-file fileb://./backend/sheffessions_api/deployment.zip
    #
