# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
name: Go

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache-dependency-path: subdir/go.sum

    - name: Fetch dependencies
      working-directory: ./backend/sheffessions_api
      run: go get -v ./...

    - name: Test
      working-directory: ./backend/sheffessions_api
      run: go test -v .

    - name: Install App Engine Go component
      run: |
        sudo apt-get install google-cloud-sdk-app-engine-go || echo "Failed to install app-engine-go, proceeding anyway."

    - name: Authenticate with GCP
      run: echo "$GOOGLE_APPLICATION_CREDENTIALS" | gcloud auth activate-service-account --key-file=-
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}


    - name: Deploy to App Engine
      run: |
        cd ./backend/sheffessions_api
        gcloud app deploy --quiet app.yaml --project sheffessions --version v1 --promote

