# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
name: Go

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache-dependency-path: subdir/go.sum

    - name: Fetch dependencies
      working-directory: ./backend/sheffessions_api
      run: go get -v ./...

    - name: Test
      working-directory: ./backend/sheffessions_api
      run: go test -v .

    # - id: auth
    #   name: Authenticate to Google Cloud
    #   uses: google-github-actions/auth@v0.4.0
    #   with:
    #     credentials_json: ${{ secrets.GCP_CREDENTIALS }}
    #
    # # - name: Change to API directory
    # #   run: cd backend/sheffessions_api
    #
    # - name: Deploy to App Engine
    #   run: gcloud app deploy --quiet --format json app.yaml --project sheffessions --promote
    #   working-directory: ./backend/sheffessions_api
    #
    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@master
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    # Optional: Build/compile step for your application, if necessary

    - name: Deploy to App Engine
      run: |
        gcloud app deploy ./backend/sheffessions_api/app.yaml --project sheffessions --quiet
