name: Check migration prefixes

on:
  pull_request:
    branches: [
      "development",
    ]

jobs:
  check-migrations:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check for migration filename prefix collisions
      run: |
        # Check out PR changes
        git fetch origin $GITHUB_REF
        git checkout FETCH_HEAD

        # Store list of migration prefixes in PR
        pr_migrations_prefixes=$(ls db/migrations | cut -d'_' -f1 | sort | uniq)

        # Check out develop branch
        git checkout develop

        # Compare migration prefixes
        for prefix in $pr_migrations_prefixes; do
          if ls db/migrations | grep -q "^${prefix}_"; then
            echo "Collision detected for migration prefix: $prefix"
            exit 1
          fi
        done

        echo "No migration prefix collisions detected."

