# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
name: Sheffessions pipeline 

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  unit-test-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        # cache-dependency-path: subdir/go.sum

    # Cache Go modules
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('./backend/sheffessions_api/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Fetch dependencies
      working-directory: ./backend/sheffessions_api
      run: go get -v ./...

    - name: Run backend/sheffessions_api unit tests
      working-directory: ./backend/sheffessions_api
      run: go test -v *_unit_test.go

  unit-test-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # You can set this to your project's Node.js version

    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: ~/.pnpm-cache
        key: ${{ runner.OS }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.OS }}-pnpm-

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      working-directory: ./frontend/sheffessions
      run: pnpm install
    
    - name: Run frontend/sheffessions unit tests
      working-directory: ./frontend/sheffessions
      run: pnpm test:unit

  integration-test:
    needs: [unit-test-backend, unit-test-frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          # cache-dependency-path: subdir/go.sum

      # Cache Go modules
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('./backend/sheffessions_api/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # This part assumes you might have dependencies for your integration tests.
      - name: Fetch dependencies
        working-directory: ./backend/sheffessions_api
        run: go get -v ./...

      # Cache pnpm modules
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-cache
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        working-directory: ./frontend/sheffessions
        run: pnpm install

      # Build and run the backend (assuming you have a main.go that starts your server)
      - name: Build and Run Backend
        working-directory: ./backend/sheffessions_api
        run: |
          go build -o server main.go
          ./server &

      - name: Wait for Backend to Start
        run: |
          while ! curl -s localhost:8080 > /dev/null; do
            sleep 5
          done

      - name: Run Backend Integration Tests
        working-directory: ./backend/sheffessions_api
        run: go test -v *_integration_test.go

      - name: Run Frontend Integration Tests
        working-directory: ./frontend/sheffessions
        run: |
          pnpm test:integration

      - name: Shutdown Backend
        if: always()
        run: pkill server
        # This assumes that "server" is the process name of your backend.

  deploy:
    needs: [unit-test-backend, unit-test-frontend, integration-test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Authenticate with GCP
      run: echo "$GOOGLE_APPLICATION_CREDENTIALS" | gcloud auth activate-service-account --key-file=-
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: sheffessions
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true

    - name: Deploy to App Engine via Cloud Build
      id: deploy
      run: |
        gcloud builds submit backend/sheffessions_api --config backend/sheffessions_api/cloudbuild.yaml
      continue-on-error: true  # Allow subsequent steps to run even if this step fails

    - name: Rollback if deployment failed
      if: steps.deploy.outcome == 'failure'
      run: |
        echo "Deployment failed. Rolling back to the previous version."
        PREVIOUS_VERSION=$(gcloud app versions list --sort-by=~LAST_DEPLOYED --limit=2 | awk 'NR==2{print $2}')
        gcloud app versions migrate $PREVIOUS_VERSION
