name: Tear Down Staging Instance

on:
  schedule:
    - cron: '0 4 * * *'  # This runs at 4 AM every day

jobs:
  teardown:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS_STAGING }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Tear Down PostgreSQL Instance on Cloud SQL'
      run: |
        gcloud sql instances patch sheffessions-staging-postgresql --no-deletion-protection
        gcloud sql instances delete sheffessions-staging-postgresql --project=sheffessions-staging --quiet

